name: 04 - Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Printing Folders Before Checkout
        run: ls -la
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Printing Folders
        run: ls -la
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
      - name: Install Dependencies
        run: npm ci

    # 0. Checkout the code from the repository
    # 1. Install dependencies of our react application
    # 2. Execute automated tests
