name: 12 - Working with Outputs

on:
  workflow_dispatch:
    inputs:
      build-status:
        type: choice
        options:
          - success
          - failure
        default: success

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-status: ${{ steps.build.outputs.status }} // status is the output from the build step (unrelated to build-status input from workflow_dispatch event)
    steps:
      - name: Print GITHUB_OUTPUT path
        run: echo "$GITHUB_OUTPUT"
      - name: Build
        id: build
        run: echo "status=${{ inputs.build-status }}" >> "$GITHUB_OUTPUT" // build-status is the input from the workflow_dispatch event (unrelated to status output from the build step)

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.build-status == 'status=success' }}
    steps:
      - name: Deploy
        run: echo "Deploying"
